=== xerip/XML_TP/TP2/exemple.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!ELEMENT stock    (produit+,quantite*, untruc)>
<!ELEMENT untruc  (nom)>
<!ELEMENT produit  (nom,prix?)>
<!ELEMENT nom      (#PCDATA)>
<!ELEMENT quantite      (#PCDATA)>

<!ELEMENT prix     (#PCDATA)>
<!ATTLIST prix
    monnaie (Euros|Francs) #IMPLIED
    >


<!ENTITY  testEntity  "salut" >

=== xerip/XML_TP/TP2/test1.xml
<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE stock SYSTEM "exemple.dtd">
<stock>
  <?xml-stylesheet
    href="monStyle.css" media="screen"
    title="Compact" type="text/css" ?>
  <produit>
    <nom> Découvrir &testEntity;  <![CDATA[ XML ]]> </nom>
    <!--Ceci est un commentaire -->
    <prix monnaie="Francs"> 100 </prix>
  </produit>
  <produit>
  <nom> DVD </nom>
 </produit>
 <untruc>
  	<nom> bleuh </nom>
  </untruc>
</stock>

=== xerip/XML_TP/TP2/exemple.xml
<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE stock SYSTEM "exemple.dtd">
<stock>
  <?xml-stylesheet
    href="monStyle.css" media="screen"
    title="Compact" type="text/css" ?>
  <produit>
    <nom> Découvrir &testEntity;  <![CDATA[ XML ]]> </nom>
    <!--Ceci est un commentaire -->
    <prix monnaie="Euros"> 50 </prix>
  </produit>
  <produit>
  <nom> CD </nom>
 </produit>
 <untruc>
  	<nom> bla </nom>
  </untruc>
</stock>
