=== xerip/XML_TP/TP6/master.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!-- entites -->
<!ENTITY lum "Campus de Luminy" >
<!ENTITY stj "Campus de Saint-Jérôme" >
<!ENTITY mail "@univ-amu.fr" >
<!ENTITY lif "http://pageperso.lif.univ-mrs.fr/~" >
<!ENTITY ueo "Unités obligatoires" >
<!ENTITY cac "crédits à choisir" >

<!ELEMENT master (intervenant+, ue+, parcours+)>

<!-- elements de master -->
<!ELEMENT intervenant (nom,email?,web?)>
<!ELEMENT parcours (responsable+,nom,description,debouches?,semestre+)>


<!-- elements de parcours -->
<!ELEMENT responsable (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT debouches (#PCDATA)>
<!ELEMENT semestre (bloc+)>

<!-- elements de semestre -->
<!ELEMENT role (#PCDATA)>
<!ELEMENT bloc (role,ref-ue+)>
<!ELEMENT ue (ref-intervenant?,nom,credit,resume,plan?,lieu)>

<!-- elements nom pour plusieurs elements-->
<!ELEMENT nom (#PCDATA)>

<!-- elements de ue -->
<!ELEMENT credit (#PCDATA)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT plan (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT ref-intervenant ANY>
<!ELEMENT ref-ue ANY>

<!-- elements de intervenant -->
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>

<!-- elements de ue et intervenant -->
<!ELEMENT id (#PCDATA)>

<!-- relations -->
<!ATTLIST intervenant id ID #IMPLIED>
<!ATTLIST ref-intervenant ref IDREF #IMPLIED>
<!ATTLIST ue id ID #IMPLIED>
<!ATTLIST ref-ue ref IDREF #IMPLIED>

=== xerip/XML_TP/TP6BOLD/master.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE master SYSTEM "master.dtd">

<master>
	<intervenant id="arrighi">
		<nom>Arrighi Pablo</nom>
		<email>pablo.ARRIGHI&mail;</email>
		<web>&lif;pablo.arrighi/</web>
	</intervenant>
	<intervenant id="morin">
		<nom>Morin Rémi</nom>
		<email>remi.MORIN&mail;</email>
		<web>&lif;remi.morin/</web>
	</intervenant>
	<intervenant id="olive">
		<nom>Olive Frédéric</nom>
		<email>frederic.olive&mail;</email>
		<web>&lif;frederic.olive/</web>
	</intervenant>
	<intervenant id="godard">
		<nom>Godard Emmanuel</nom>
		<email>emmanuel.godard&mail;</email>
		<web>&lif;emmanuel.godard/</web>
	</intervenant>
	<intervenant id="santocanale">
		<nom>Santocanale Luigi</nom>
		<email>luigi.santocanale&mail;</email>
		<web>&lif;luigi.santocanale/</web>
	</intervenant>
	<intervenant id="sabatier">
		<nom>Sabatier Claude</nom>
		<email>claude.sabatier&mail;</email>
		<web>&lif;claude.sabatier/</web>
	</intervenant>
	<intervenant id="bechet">
		<nom>Bechet Frédéric</nom>
		<email>frederic.BECHET&mail;</email>
		<web>&lif;frederic.bechet/</web>
	</intervenant>
	<intervenant id="reynier">
		<nom>Reynier Pierre-Alain</nom>
		<email>pierre-alain.reynier&mail;</email>
		<web>&lif;pierre-alain.reynier/</web>
	</intervenant>
	<intervenant id="dal-molin">
		<nom>Dal Molin Alain</nom>
		<email>alain.dal-molin&mail;</email>
		<web>&lif;alain.dal-molin/</web>
	</intervenant>
	<intervenant id="rene-chabarot">
		<nom>Rene Chabarot Lydie</nom>
		<email>lydie.rene&mail;</email>
		<web>irsic.univ-amu.fr/Lydie-RENE/</web>
	</intervenant>
	<intervenant id="massat">
		<nom>Massat Jean-Luc</nom>
		<email>jean-luc.massat&mail;</email>
		<web>&lif;jean-luc.massat/</web>
	</intervenant>
	<intervenant id="habet">
		<nom>HABET Djamal</nom>
		<email>djamal.habet&mail;</email>
		<web>&lif;djamal.habet/</web>
	</intervenant>
	<intervenant id="artieres">
		<nom>Thierry ARTIÈRES</nom>
		<email>thierry.artieres&mail;</email>
		<web>&lif;thierry.artieres/</web>
	</intervenant>

	
	<ue id="ENSINAU1">
		<ref-intervenant ref="arrighi" />
		<nom>Génie logiciel</nom>
		<credit>6</credit>
		<resume>			
			Processus logiciel
			Gestion de projet
			Spécification et conception (artefact : notation UML)
			Design patterns
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU2">
		<ref-intervenant ref="olive" />
		<nom>Complexité</nom>
		<credit>6</credit>
		<resume>						
			Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.
			Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.
			Classes P et NP. Problèmes NP-complets.
			Méthodes de résolution des problèmes NP-Complets.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU3">
		<ref-intervenant ref="godard" />
		<nom>Réseaux</nom>
		<credit>6</credit>
		<resume>						
			Architecture en couches, standard OSI
			Couche physique
			Couche liaison de Données
			Réseau IP
			Algorithmes de routage, routage IP
			Protocole TCP/IP
			Couche Application : HTTP, SMTP, FTP, ...
			Bases des protocoles cryptographiques (terminologie, architecture à clef publique).
			Introduction à la Sécurité des réseaux.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU4">
		<ref-intervenant ref="santocanale" />
		<nom>Programmation fonctionnelle</nom>
		<credit>3</credit>
		<resume>						
			1- Introduction à la programmation fonctionnelle, sur l'exemple du langage
			OCaml
			Expressions, évaluation, types de base. Polymorphisme, ordre supérieur.
			Fonctions récursives, filtrage. Les diverses stratégies d'évaluation, application à la programmation d'un opérateur de point fixe.
			2- Les types
			Sommes, types récursifs, polymorphes. Arbres. Filtrage.
			3- Sémantique opérationnelle
			Liaisons, environnements, clôtures. Évaluation des fonctions récursives .
			4- Aspects impératifs
			Exceptions, entrées-sorties, séquencement, fichiers, références, tableaux, enregistrements.
			5- Implantation du filtrage en OCaml
			Termes formels, substitutions, filtrage.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU12">
		<ref-intervenant ref="sabatier" />
		<nom>BDR : Approfondissement</nom>
		<credit>3</credit>
		<resume>						
			Nous sommes désolé, mais nous n'avons pas encore de résumé.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU6">
		<nom>Programmation logique</nom>
		<credit>3</credit>
		<resume>
			Introduction. Forme générale des règles. Effacement, unification, backtracking. Contrôle de l'exécution.
			Listes, arbres et n-uplets. Liste représentée par différence de listes. Ajout en tête et en queue, concaténation.
			Analyseurs syntaxiques. Construction d'un arbre syntaxique. Liste des feuilles d'un arbre. Freeze et analyse par feuille.
			Règles prédéfinies.	
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU7">
		<nom>Outils de l'internet</nom>
		<credit>3</credit>
		<resume>		
			Présentation d'Internet.
			Les langages et les normes sur Internet.
			Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3
			Les applications web.
			Sécurité.
			Les nouvelles et futures technologies.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU8">
		<nom>Systèmes embarqués</nom>
		<credit>3</credit>
		<resume>		
			Nous sommes désolé, mais nous n'avons pas encore de résumé.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU9">
		<ref-intervenant ref="bechet" />
		<nom>Fondamentaux pour l'ingénierie des langues</nom>
		<credit>3</credit>
		<resume>						
			Rappel de théorie des langages
			Algorithmes d'analyse syntaxique pour grammaires ambiguës
			Transducteurs finis et leur application en TAL
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU10">
		<ref-intervenant ref="reynier" />
		<nom>Modèles à évènements discrets</nom>
		<credit>3</credit>
		<resume>						
			Posséder les notions de base en modélisation et analyse de systèmes dynamiques à événements discrets et particulièrement appréhender le formalisme réseau de
			Pétri. Étudier la conception et la spécification des systèmes réactifs à travers l'analyse du modèle à évènements discrets (concurrence, parallélisme, synchronisation).
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU13">
		<nom>Pratique de la cryptographie</nom>
		<credit>3</credit>
		<resume>		
			Nous sommes désolé, mais nous n'avons pas encore de résumé.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU9">
		<ref-intervenant ref="dal-molin" />
		<nom>Anglais</nom>
		<credit>3</credit>
		<resume>						
			Un enseignement destiné à confirmer l'utilisation de l'anglais dans le contexte de l'informatique ainsi que dans la pratique professionnelle.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU2">
		<ref-intervenant ref="rene-chabarot" />
		<nom>Communication</nom>
		<credit>3</credit>
		<resume>						
			chapitre 1  : Théories de la communication :
				1.1 La théorie mathématique de l’information (Shannon, Weaver), la cybernétique (Wiener)
				1.2 La théorie de Palo Alto ( Bateson, Watzlawick) et la théorie de la communication par les processus (Mucchielli)
			chapitre 2 : Rôle de l’interculturalité dans le travail en équipe :
				2.1 L’enquête interculturelle de Hofstede pour IBM
				2.2 La gestuelle et le paralangage et la proxémie dans le monde (Hall)
			chapitre 3 : Notions de management et de travail collaboratif
				3.1 Le travail collaboratif vs le travail coopératif
				3.2 La notion de groupes
				3.3 Les compétences managériales
			Pré-requis :
			Particulièrement utile pour un choix d’options, les échanges internationaux et la formation continue.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU4">
		<ref-intervenant ref="massat" />
		<nom>XML</nom>
		<credit>3</credit>
		<resume>
			XML, DTD, XSD
			XPath, XSLT, XQuery
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU5">
		<nom>Algorithmique et recherche opérationnelle</nom>
		<credit>3</credit>
		<resume>		
			Programmation linéaire.
			Notions et algorithmes de flots.
			Applications (couplage, affectation, transport, ...)
			Programmation dynamique (sac à dos, ordonnancement, ...)
			Algorithmes à performance garantie
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINBU15">
		<ref-intervenant ref="morin" />
		<nom>Programmation parallèle</nom>
		<credit>3</credit>
		<resume>		
			Nous sommes désolé, mais nous n'avons pas encore de résumé.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINCU6">
		<nom>Projet</nom>
		<credit>6</credit>
		<resume>		
			Le but du projet est de mettre en oeuvre, de l'analyse à la programmation, les notions présentées en cours. C'est l'occasion, pour les étudiants, d'utiliser sur un cas pratique, les éléments exposées dans les UE. Travail effectué sous la direction pédagogique d'un enseignant, et donnant lieu à la rédaction d'un mémoire et d'une soutenance orale.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU7">
		<nom>Stage</nom>
		<credit>6</credit>
		<resume>		
			Le but du projet est de mettre en oeuvre, de l'analyse à la programmation, les notions présentées en cours. C'est l'occasion, pour les étudiants, d'utiliser sur un cas pratique, les éléments exposées dans les UE. Travail effectué sous la direction pédagogique d'un enseignant, et donnant lieu à la rédaction d'un mémoire et d'une soutenance orale.
		</resume>
		<lieu>&lum;</lieu>
	</ue>
	<ue id="ENSINAU8">
		<nom>Sémantique</nom>
		<credit>3</credit>
		<resume>		
			1-Le lambda-calcul simplement typé
			Syntaxe, typage, beta et eta-conversions, équations. Modèles : interprétation des jugements de typage.
			2-Extension à PCF. La règle \mu.
			3-Points fixes dans les ordres partiels complets.
			Le théorème de Tarski.
			4-Sémantique par point fixe de PCF.
			5-Cours de clôture : survol des différentes approches sémantiques.
			Sémantiques opérationnelles : par transitions, naturelles, machine abstraite de Landin.
			Sémantique dénotationnelles : cas fonctionnel(cf.chapitre 4) et cas d'un petit langage impératif.
		</resume>
